trigger: none
pr: none

pool:
  name: Default

variables:
- group: "Chatwork Notifications"
- group: "Otogi Versions"

parameters:
- name: TargetEnvironment
  displayName: Environment
  type: string
  default: develop
  values:
    - develop
    - dev02

stages:
  - stage: BuildWebGLBase_Stage
    displayName: Build WebGL
    dependsOn: []
    variables:
      versionCode: $[ variables['PV VersionCode/${{ parameters.TargetEnvironment }}'] ]
    jobs:
    - job: Test
      displayName: Test
      steps:
      - powershell: |
          $message = "${{ parameters.TargetEnvironment }}-WebGL v$(displayVersion) ($(versionCode)): ゲームビルド始まっちゃったよ～"
          $message += "$(CN Takeba 100)"

          $body = @{"body"= $message}
          $url = "$(CN Main Channel Url)"
          $headers = @{"X-ChatWorkToken" = "$(CN Token)"}
          Invoke-WebRequest -Method Post -Uri $url -Body $body -ContentType "application/x-www-form-urlencoded" -Headers $headers -UseBasicParsing
        displayName: Send WebGL build started notification