stages:
  - stage: BuildWebGLBase_Stage
    displayName: Build WebGL
    dependsOn: []
    jobs:
    - job: Test
      displayName: Test
      steps:
      - powershell: |
          Write-Output Neko
        displayName: Test PS